<def f='include/boost/graph/exception.hpp' l='19' type='void boost::bad_graph::bad_graph(const std::string &amp; what_arg)'/>
<use f='include/boost/graph/exception.hpp' l='25' u='c' c='_ZN5boost9not_a_dagC1Ev'/>
<use f='include/boost/graph/exception.hpp' l='31' u='c' c='_ZN5boost13negative_edgeC1Ev'/>
<use f='include/boost/graph/exception.hpp' l='37' u='c' c='_ZN5boost14negative_cycleC1Ev'/>
<use f='include/boost/graph/exception.hpp' l='43' u='c' c='_ZN5boost13not_connectedC1Ev'/>
<use f='include/boost/graph/exception.hpp' l='49' u='c' c='_ZN5boost12not_completeC1Ev'/>
