<dec f='include/c++/4.9/exception' l='64' type='void std::exception::~exception()'/>
<ovr f='TrinityCore3.3.5/src/server/shared/Packets/ByteBuffer.h' l='44' c='_ZN19ByteBufferExceptionD1Ev'/>
<ovr f='TrinityCore3.3.5/src/server/database/Updater/DBUpdater.h' l='30' c='_ZN15UpdateExceptionD1Ev'/>
<ovr f='TrinityCore6.x/src/server/database/Updater/DBUpdater.h' l='30' c='_ZN15UpdateExceptionD1Ev'/>
<ovr f='TrinityCore6.x/src/server/shared/Packets/ByteBuffer.h' l='43' c='_ZN19ByteBufferExceptionD1Ev'/>
