<def f='include/c++/4.9/future' l='1198' type='void std::promise&lt;void&gt;::set_exception(std::__exception_ptr::exception_ptr __p)'/>
