<dec f='include/c++/4.9/exception' l='127' type='bool std::uncaught_exception()'/>
<use f='include/c++/4.9/ostream' l='431' u='c' c='_ZNSt13basic_ostream6sentryD1Ev'/>
<doc f='include/c++/4.9/exception' l='116'>/** [18.6.4]/1:  &apos;Returns true after completing evaluation of a
   *  throw-expression until either completing initialization of the
   *  exception-declaration in the matching handler or entering @c unexpected()
   *  due to the throw; or after entering @c terminate() for any reason
   *  other than an explicit call to @c terminate().  [Note: This includes
   *  stack unwinding [15.2].  end note]&apos;
   *
   *  2: &apos;When @c uncaught_exception() is true, throwing an
   *  %exception can result in a call of @c terminate()
   *  (15.5.1).&apos;
   */</doc>
<use f='include/c++/4.9/condition_variable' l='191' u='c' c='_ZNSt3_V222condition_variable_any7_UnlockD1Ev'/>
