<inh f='include/c++/4.9/stdexcept' l='82' c='std::invalid_argument'/>
<def f='include/boost/graph/exception.hpp' l='18'/>
<ovr f='include/boost/graph/exception.hpp' l='23' c='boost::not_a_dag'/>
<ovr f='include/boost/graph/exception.hpp' l='29' c='boost::negative_edge'/>
<ovr f='include/boost/graph/exception.hpp' l='35' c='boost::negative_cycle'/>
<ovr f='include/boost/graph/exception.hpp' l='41' c='boost::not_connected'/>
<ovr f='include/boost/graph/exception.hpp' l='47' c='boost::not_complete'/>
<size>16</size>
