<inh f='include/c++/4.9/stdexcept' l='112' c='std::runtime_error'/>
<def f='TrinityCore6.x/dep/zmqpp/zmqpp/exception.hpp' l='31'/>
<ovr f='TrinityCore6.x/dep/zmqpp/zmqpp/exception.hpp' l='49' c='zmqpp::invalid_instance'/>
<ovr f='TrinityCore6.x/dep/zmqpp/zmqpp/exception.hpp' l='64' c='zmqpp::zmq_internal_exception'/>
<size>16</size>
<doc f='TrinityCore6.x/dep/zmqpp/zmqpp/exception.hpp' l='21'>/*!
 * Represents the base zmqpp exception.
 *
 * All zmqpp runtime exceptions are children of this class.
 * The class itself does not provide any special access fields but it only
 * for convince when catching exceptions.
 *
 * The class extends std::runtime_error.
 *
 */</doc>
